[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.74.3"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"

[[redirects]]
  from = "en/*"
  to = "en/404.html"
  status = 404

[[redirects]]
  from = "hi/*"
  to = "hi/404.html"
  status = 404